services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: ${WP_CONTAINER}
    depends_on:
      - db
    ports:
      - '${WP_PORT}:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_SITEURL: http://localhost:${WP_PORT}
      WORDPRESS_HOME: http://localhost:${WP_PORT}
    volumes:
      - ./wp:/var/www/html
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PMA_CONTAINER}
    depends_on:
      - db
    ports:
      - '${PMA_PORT}:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASS}
    restart: unless-stopped
volumes:
  db_data:
